apiVersion: v1
kind: Service
metadata:
  name: stock-anomaly-service
  namespace: stock-anomaly
spec:
  selector:
    app: stock-anomaly-function
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer